// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package rplx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncNodeValue struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Stamp                int64    `protobuf:"varint,2,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncNodeValue) Reset()         { *m = SyncNodeValue{} }
func (m *SyncNodeValue) String() string { return proto.CompactTextString(m) }
func (*SyncNodeValue) ProtoMessage()    {}
func (*SyncNodeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_8096b1e50141cb19, []int{0}
}
func (m *SyncNodeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncNodeValue.Unmarshal(m, b)
}
func (m *SyncNodeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncNodeValue.Marshal(b, m, deterministic)
}
func (dst *SyncNodeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncNodeValue.Merge(dst, src)
}
func (m *SyncNodeValue) XXX_Size() int {
	return xxx_messageInfo_SyncNodeValue.Size(m)
}
func (m *SyncNodeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncNodeValue.DiscardUnknown(m)
}

var xxx_messageInfo_SyncNodeValue proto.InternalMessageInfo

func (m *SyncNodeValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SyncNodeValue) GetStamp() int64 {
	if m != nil {
		return m.Stamp
	}
	return 0
}

type SyncVariable struct {
	// map key - nodeID
	NodesValues          map[string]*SyncNodeValue `protobuf:"bytes,1,rep,name=NodesValues,proto3" json:"NodesValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TTL                  int64                     `protobuf:"varint,2,opt,name=TTL,proto3" json:"TTL,omitempty"`
	TTLStamp             int64                     `protobuf:"varint,3,opt,name=TTLStamp,proto3" json:"TTLStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SyncVariable) Reset()         { *m = SyncVariable{} }
func (m *SyncVariable) String() string { return proto.CompactTextString(m) }
func (*SyncVariable) ProtoMessage()    {}
func (*SyncVariable) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_8096b1e50141cb19, []int{1}
}
func (m *SyncVariable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncVariable.Unmarshal(m, b)
}
func (m *SyncVariable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncVariable.Marshal(b, m, deterministic)
}
func (dst *SyncVariable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncVariable.Merge(dst, src)
}
func (m *SyncVariable) XXX_Size() int {
	return xxx_messageInfo_SyncVariable.Size(m)
}
func (m *SyncVariable) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncVariable.DiscardUnknown(m)
}

var xxx_messageInfo_SyncVariable proto.InternalMessageInfo

func (m *SyncVariable) GetNodesValues() map[string]*SyncNodeValue {
	if m != nil {
		return m.NodesValues
	}
	return nil
}

func (m *SyncVariable) GetTTL() int64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *SyncVariable) GetTTLStamp() int64 {
	if m != nil {
		return m.TTLStamp
	}
	return 0
}

type SyncRequest struct {
	NodeID string `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	// map key - variable name
	Variables            map[string]*SyncVariable `protobuf:"bytes,2,rep,name=Variables,proto3" json:"Variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_8096b1e50141cb19, []int{2}
}
func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (dst *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(dst, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SyncRequest) GetVariables() map[string]*SyncVariable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type SyncResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_8096b1e50141cb19, []int{3}
}
func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (dst *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(dst, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

func (m *SyncResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncNodeValue)(nil), "rplx.SyncNodeValue")
	proto.RegisterType((*SyncVariable)(nil), "rplx.SyncVariable")
	proto.RegisterMapType((map[string]*SyncNodeValue)(nil), "rplx.SyncVariable.NodesValuesEntry")
	proto.RegisterType((*SyncRequest)(nil), "rplx.SyncRequest")
	proto.RegisterMapType((map[string]*SyncVariable)(nil), "rplx.SyncRequest.VariablesEntry")
	proto.RegisterType((*SyncResponse)(nil), "rplx.SyncResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicatorClient is the client API for Replicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicatorClient interface {
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type replicatorClient struct {
	cc *grpc.ClientConn
}

func NewReplicatorClient(cc *grpc.ClientConn) ReplicatorClient {
	return &replicatorClient{cc}
}

func (c *replicatorClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/rplx.Replicator/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicatorServer is the server API for Replicator service.
type ReplicatorServer interface {
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
}

func RegisterReplicatorServer(s *grpc.Server, srv ReplicatorServer) {
	s.RegisterService(&_Replicator_serviceDesc, srv)
}

func _Replicator_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rplx.Replicator/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replicator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rplx.Replicator",
	HandlerType: (*ReplicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Replicator_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_8096b1e50141cb19) }

var fileDescriptor_message_8096b1e50141cb19 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x14, 0x74, 0x4b, 0xdb, 0xd8, 0x87, 0x35, 0xf5, 0x69, 0x0c, 0xe1, 0xd4, 0xe0, 0x05, 0x2f, 0x98,
	0xe0, 0xc5, 0x68, 0xf4, 0xa2, 0x3d, 0x98, 0x34, 0xc6, 0x2c, 0xa4, 0xf7, 0x6d, 0xbb, 0x31, 0x8d,
	0x94, 0x45, 0x96, 0x1a, 0xf9, 0x32, 0x7f, 0xc5, 0xcf, 0x31, 0xbb, 0x4b, 0x81, 0x5a, 0x6f, 0xef,
	0xcd, 0xce, 0xcc, 0xce, 0xb0, 0xc0, 0x70, 0xcd, 0xa5, 0x64, 0x6f, 0x3c, 0xc8, 0x72, 0x51, 0x08,
	0xec, 0xe6, 0x59, 0xf2, 0xe5, 0xdd, 0xc1, 0x30, 0x2a, 0xd3, 0xc5, 0x8b, 0x58, 0xf2, 0x19, 0x4b,
	0x36, 0x1c, 0xcf, 0xa0, 0xa7, 0x07, 0x87, 0x8c, 0x89, 0x6f, 0xd1, 0x5e, 0x8d, 0x46, 0x05, 0x5b,
	0x67, 0x4e, 0xc7, 0xa0, 0x7a, 0xf1, 0x7e, 0x08, 0x1c, 0x29, 0xf5, 0x8c, 0xe5, 0x2b, 0x36, 0x4f,
	0x38, 0x4e, 0xc0, 0x56, 0x4e, 0x52, 0x8b, 0xa4, 0x43, 0xc6, 0x96, 0x6f, 0x87, 0x17, 0x81, 0xba,
	0x29, 0x68, 0x13, 0x83, 0x16, 0x6b, 0x92, 0x16, 0x79, 0x49, 0xdb, 0x3a, 0x1c, 0x81, 0x15, 0xc7,
	0xd3, 0xea, 0x2e, 0x35, 0xa2, 0x0b, 0x87, 0x71, 0x3c, 0x35, 0x11, 0x2c, 0x0d, 0xd7, 0xbb, 0x1b,
	0xc1, 0xe8, 0xaf, 0x9d, 0x72, 0x78, 0xe7, 0xa5, 0xee, 0x30, 0xa0, 0x6a, 0xc4, 0x4b, 0xe8, 0x7d,
	0xea, 0x5e, 0xca, 0xd5, 0x0e, 0x4f, 0x9b, 0x50, 0x75, 0x77, 0x6a, 0x18, 0xb7, 0x9d, 0x1b, 0xe2,
	0x7d, 0x13, 0xb0, 0xd5, 0x21, 0xe5, 0x1f, 0x1b, 0x2e, 0x0b, 0x3c, 0x87, 0xbe, 0xe2, 0x3d, 0x3f,
	0x55, 0x9e, 0xd5, 0x86, 0x0f, 0x30, 0xd8, 0x96, 0x92, 0x4e, 0x47, 0xf7, 0x1d, 0x37, 0xd6, 0x95,
	0x3a, 0xa8, 0x29, 0xa6, 0x6c, 0x23, 0x71, 0x5f, 0xe1, 0x78, 0xf7, 0xf0, 0x9f, 0xe8, 0xfe, 0x6e,
	0x74, 0xdc, 0xff, 0x9e, 0xed, 0xe4, 0x9e, 0x79, 0x13, 0xca, 0x65, 0x26, 0x52, 0xc9, 0x11, 0xa1,
	0xfb, 0x28, 0x96, 0xdb, 0xf7, 0xd4, 0x73, 0x78, 0x0f, 0x40, 0x79, 0x96, 0xac, 0x16, 0xac, 0x10,
	0x39, 0x5e, 0x41, 0x57, 0x29, 0xf0, 0x64, 0x2f, 0xb8, 0x8b, 0x6d, 0xc8, 0x18, 0x7a, 0x07, 0xf3,
	0xbe, 0xfe, 0x83, 0xae, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x25, 0x6c, 0x4c, 0x52, 0x02,
	0x00, 0x00,
}
